apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-products-hpa
  namespace: ms-products-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-products-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75 # Ajusta este valor según el comportamiento de tu aplicación
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300 # Evita un escalado rápido y poco estable
      selectPolicy: Max
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60 # Escala en incrementos de hasta 2 pods por minuto
    scaleDown:
      stabilizationWindowSeconds: 300 # Evita reducir las réplicas demasiado rápido
      selectPolicy: Max
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60 # Escala hacia abajo de manera gradual
