apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ms-products-ingress
  namespace: ms-products-namespace
spec:
  ingressClassName: nginx
  rules:
    - host: jva-cloud.org
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: ms-products-service
                port:
                  number: 9090
